name: Cypress Tests with Dependency and Artifact Caching

on: [push]

jobs:
  # install:
  # ....
  cypress-run:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node16.16.0-chrome105-ff104-edge
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Cypress Test
        uses: cypress-io/github-action@v5.5.1
        with:
          command: npx cypress run
          browser: chrome
      - name: Upload screenshots
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: ./cypress/screenshots
      - name: Upload videos
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-videos
          path: ./cypress/videos
